### PR TITLE
Suppress Mongo log output in specs

### PR DESCRIPTION
**Pull request by maxjacobson**
Just to put the focus on the green dots

### CODE REVIEW

**Comment by maxjacobson** [comment]
started getting curious about how this works after reading [your post](http://maximomussini.com/posts/mongoid-n+1/) :smile:

**Comment by ElMassimo** [comment]
This will only work for Mongoid 5, right? Thanks! :smiley:

**Comment by ElMassimo** [comment]
By the way, going to write about this gem and its use cases soon, the readme is very thin :smiley:

**Comment by maxjacobson** [comment]
Yea, the Mongo constant is only defined when using Mongoid5. That was the default Mongoid when I cloned and ran the tests -- not sure if there's log output when running tests for Mongoid 4. Actually not really sure *how* to run the tests for Mongoid 4 haha

**Comment by ElMassimo** [comment]
You would need to `export BUNDLE_GEMFILE=$PWD/gemfiles/mongoid4.gemfile`, install the dependencies, and run the tests as usual.

**Comment by maxjacobson** [comment]
aha neat. Just tried it -- no log output for mongoid4.gemfile :+1:

**Pull request merged**
